theme:
  name: material
  features:
    - navigation.sections # Sections are included in the navigation on the left.
    - toc.integrate # Table of contents is integrated on the left; does not appear separately on the right.
    - header.autohide # header disappears as you scroll
  palette:
    # Light mode / dark mode
    # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
    # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github # GitHub logo in top right
  logo: "_static/favicon.png" # Our logo in top left
  favicon: "_static/favicon.png"
  # custom_dir: "docs/_overrides" # Overriding part of the HTML

site_name: Unxt
site_description: The documentation for the unxt software library.
site_author: GalacticDynamics
site_url: https://unxt.readthedocs.io/en/latest/

repo_url: https://github.com/GalacticDynamics/unxt
repo_name: GalacticDynamics/unxt
edit_uri: "" # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: true # Don't allow warnings during the build process

extra_javascript:
  # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - _static/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - _static/custom_css.css

markdown_extensions:
  - pymdownx.arithmatex: # Render LaTeX via MathJax
      generic: true
  - pymdownx.superfences # Seems to enable syntax highlighting when used with the Material theme.
  - pymdownx.details # Allowing hidden expandable regions denoted by ???
  - pymdownx.snippets: # Include one Markdown file into another
      base_path: docs
  - admonition
  - toc:
      permalink: "¤" # Adds a clickable permalink to each section heading
      toc_depth: 3

plugins:
  - search # default search plugin; needs manually re-enabling when using any other plugins
  - autorefs # Cross-links to headings
  - include_exclude_files:
      # include:
      #   - ".htaccess"
      exclude:
        - "_overrides"
  - mknotebooks # Jupyter notebooks
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import pytkdocs_tweaks
            - pytkdocs_tweaks.main()
            - import jaxtyping
            - jaxtyping.set_array_name_format("array")

          options:
            allow_inspection: true
            docstring_style: numpy
            heading_level: 2
            inherited_members: true # Allow looking up inherited methods
            members_order: source # order methods according to their order of definition in the source code, not alphabetical order
            show_bases: true
            show_if_no_docstring: true
            show_inheritance_diagram: true
            show_root_full_path: true # display "diffrax.asdf" not just "asdf"
            show_root_heading: true # actually display anything at all...
            show_signature_annotations: true
            show_signature_return_annotation: true
            show_signature_parameter_types: true
          external:
            numpy: https://numpy.org/doc/stable/

nav:
  - "index.md"
  - API:
      - "api/quantities.md"
      - "api/unitsystems.md"
      - "api/experimental.md"
  - Interoperability:
      - "interop.md"
  - Tutorials:
      - "tutorials/diffrax.md"
