# Type stub for `unxt.quantity`.
#
# Exists for mypy alone: `pyright`/`ty` already resolve this module correctly
# from the real `.py` sources (including `Quantity.__class_getitem__`), so
# this stub's only job is to patch what mypy gets wrong there -- primarily
# that `Quantity`'s `value`/`unit` fields are `equinox.field(converter=...)`,
# whose externally-accepted type mypy cannot infer from the converter.
#
# A `.pyi` fully shadows its `.py` module for every type checker, so this
# file must stay a complete, accurate mirror of `unxt/quantity.py`'s public
# surface -- an omission here does not fall back to the real source, it makes
# that name invisible to mypy/pyright/ty alike.
#
# `Quantity` is *not* generic at runtime: `Quantity["time"]` is a documented
# no-op (`__class_getitem__` returns the class unchanged; the
# dimension-checked, truly parametric type is
# `unxts.parametric.ParametricQuantity`). This stub deliberately does *not*
# declare `Quantity` as `Generic` to make the subscript type-check: doing so
# buys nothing (mypy still parses a bare string subscript like
# `Quantity["time"]` as a forward-reference type expression -- `Name "time"
# is not defined` -- regardless of the TypeVar's bound, unless wrapped in
# `Literal[...]`) while actively regressing the common case, since a TypeVar
# that never appears in `__init__`/methods can't be inferred from
# construction and `Quantity(1, "m")` would infer as `Quantity[Never]`
# instead of plain `Quantity`. `Quantity["time"]` still works fine as an
# *untyped* runtime call (and under pyright/ty, which read
# `__class_getitem__` directly); it just isn't something this stub can make
# mypy accept as a type annotation.

from collections.abc import Callable, Mapping, Sequence
from typing import (
    Any,
    NoReturn,
    Self,
    TypeAlias,
    TypeGuard,
    final,
    overload,
)

import jax
import numpy as np
from jaxtyping import Array, ArrayLike, Bool
from numpy.typing import NDArray
from quax import ArrayValue

from unxt.units import AbstractUnit
from unxt.unitsystems import AbstractUnitSystem

#: `ArrayLike` (jaxtyping) alone excludes plain `list`/`tuple`, which
#: `convert_to_quantity_value` accepts directly (`value.py`, `ArrayLike | list
#: | tuple` registration) -- e.g. the class docstrings' own `Quantity([1, 2,
#: 3], "m")`. Every quantity constructor's `value` param uses this, not bare
#: `ArrayLike`.
_ValueLike: TypeAlias = ArrayLike | list[Any] | tuple[Any, ...]

# ===================================================================
# Static value wrapper (StaticQuantity's storage)

@final
class StaticValue:
    def __init__(self, array: object, /) -> None: ...
    @property
    def array(self) -> NDArray[Any]: ...
    @classmethod
    def from_(cls, *args: Any, **kwargs: Any) -> Self: ...
    def __array__(self, dtype: Any = ...) -> NDArray[Any]: ...
    def __format__(self, format_spec: str, /) -> str: ...
    def __reduce__(self) -> tuple[Any, tuple[Any, ...]]: ...
    def __getattr__(self, name: str) -> Any: ...
    def __eq__(self, other: object, /) -> bool | NDArray[np.bool_]: ...  # type: ignore[override]
    def __ne__(self, other: object, /) -> bool | NDArray[np.bool_]: ...  # type: ignore[override]
    def __lt__(self, other: Any, /) -> NDArray[np.bool_]: ...
    def __le__(self, other: Any, /) -> NDArray[np.bool_]: ...
    def __gt__(self, other: Any, /) -> NDArray[np.bool_]: ...
    def __ge__(self, other: Any, /) -> NDArray[np.bool_]: ...
    def __hash__(self) -> int: ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __floordiv__(self, other: Any) -> Any: ...
    def __rfloordiv__(self, other: Any) -> Any: ...
    def __pow__(self, other: Any) -> Any: ...
    def __rpow__(self, other: Any) -> Any: ...
    def __mod__(self, other: Any) -> Any: ...
    def __rmod__(self, other: Any) -> Any: ...
    def __matmul__(self, other: Any) -> Any: ...
    def __rmatmul__(self, other: Any) -> Any: ...
    def __neg__(self) -> Any: ...
    def __pos__(self) -> Any: ...
    def __abs__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...

# ===================================================================
# Flag type for `ustrip`

class AllowValue:
    def __new__(cls) -> NoReturn: ...

# ===================================================================
# Quantity hierarchy

class AbstractQuantity(ArrayValue):
    value: Array | StaticValue
    unit: AbstractUnit

    # ---------------------------------------------------------------
    # Constructors
    @classmethod
    @overload
    def from_(cls, value: _ValueLike, unit: Any, /, *, dtype: Any = ...) -> Self: ...
    @classmethod
    @overload
    def from_(cls, value: _ValueLike, /, *, unit: Any, dtype: Any = ...) -> Self: ...
    @classmethod
    @overload
    def from_(cls, *, value: Any, unit: Any, dtype: Any = ...) -> Self: ...
    @classmethod
    @overload
    def from_(cls, mapping: Mapping[str, Any], /) -> Self: ...
    @classmethod
    @overload
    def from_(
        cls, value: AbstractQuantity, unit: Any | None = ..., /, *, dtype: Any = ...
    ) -> Self: ...

    # ---------------------------------------------------------------
    # Quantity API
    def uconvert(self, u: Any, /) -> Self: ...
    def ustrip(self, u: Any, /) -> Array: ...
    def is_equivalent(self, other: AbstractQuantity, /) -> Any: ...

    # Astropy-compatibility (AstropyQuantityCompatMixin)
    def to(self, u: Any, /) -> Self: ...
    def to_value(self, u: Any, /) -> ArrayLike: ...
    def decompose(self, bases: Sequence[AbstractUnit | str], /) -> Self: ...

    # ---------------------------------------------------------------
    # Quax / Array API
    @property
    def shape(self) -> tuple[int, ...]: ...
    def materialise(self) -> NoReturn: ...
    def aval(self) -> jax.core.ShapedArray: ...
    def enable_materialise(self, _: bool = ...) -> Self: ...
    def __array_namespace__(self, *, api_version: Any = ...) -> Any: ...
    def __array__(self, *args: object, **kw: object) -> NDArray[Any]: ...
    def __array_function__(
        self,
        func: Callable[..., Any],
        types: Any,
        args: tuple[Any, ...],
        kwargs: dict[str, Any],
    ) -> Any: ...
    def __array_ufunc__(
        self, ufunc: np.ufunc, method: str, *inputs: Any, **kwargs: Any
    ) -> Any: ...

    # attributes
    @property
    def dtype(self) -> Any: ...
    @property
    def device(self) -> jax.Device: ...
    @property
    def mT(self) -> Self: ...  # noqa: N802
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def T(self) -> Self: ...  # noqa: N802
    @property
    def sharding(self) -> Any: ...
    @property
    def at(self) -> Any: ...

    # methods
    def __bool__(self) -> bool: ...
    def __complex__(self) -> complex: ...
    def __dlpack__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __dlpack_device__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __float__(self) -> float: ...
    def __getitem__(self, key: Any) -> Self: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def to_device(self, device: jax.Device | None = ...) -> Self: ...

    # ---------------------------------------------------------------
    # JAX API
    def __len__(self) -> int: ...
    def __length_hint__(self) -> int: ...
    def __iter__(self) -> Any: ...
    def argmax(self, *args: Any, **kwargs: Any) -> Array: ...
    def argmin(self, *args: Any, **kwargs: Any) -> Array: ...
    def astype(self, *args: Any, **kwargs: Any) -> Self: ...
    def block_until_ready(self) -> Self: ...
    def devices(self) -> set[jax.Device]: ...
    def flatten(self) -> Self: ...
    def max(self, *args: Any, **kwargs: Any) -> Self: ...
    def mean(self, *args: Any, **kwargs: Any) -> Self: ...
    def min(self, *args: Any, **kwargs: Any) -> Self: ...
    def ravel(self) -> Self: ...
    def reshape(self, *args: Any, order: str = ...) -> Self: ...
    def round(self, *args: Any, **kwargs: Any) -> Self: ...
    def squeeze(self, *args: Any, **kwargs: Any) -> Self: ...

    # ---------------------------------------------------------------
    # Python stuff: equality/hash/repr (narrowed from the real `object`-typed
    # base to what `Quantity`/`Angle`, which don't override `__eq__`, actually
    # return; `StaticQuantity` overrides both below with its true broader type)
    def __eq__(self, other: object, /) -> Bool[Array, "*shape"]: ...  # type: ignore[override]
    def __ne__(self, other: object, /) -> Bool[Array, "*shape"]: ...  # type: ignore[override]
    def __hash__(self) -> int: ...

    # Arithmetic: forward ops are `Any` for real (they coerce foreign astropy
    # operands and can promote across quantity subtypes via `plum`); reflected
    # ops come straight from `quax_blocks.NumpyBinaryOpsMixin[Any, AbstractQuantity]`.
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> AbstractQuantity: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> AbstractQuantity: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> AbstractQuantity: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> AbstractQuantity: ...
    def __floordiv__(self, other: Any) -> Any: ...
    def __rfloordiv__(self, other: Any) -> AbstractQuantity: ...
    def __mod__(self, other: Any) -> Any: ...
    def __rmod__(self, other: Any) -> AbstractQuantity: ...
    def __pow__(self, other: Any) -> Any: ...
    def __rpow__(self, other: Any) -> AbstractQuantity: ...
    def __matmul__(self, other: Any) -> Any: ...
    def __rmatmul__(self, other: Any) -> AbstractQuantity: ...
    def __divmod__(self, other: Any) -> AbstractQuantity: ...
    def __rdivmod__(self, other: Any) -> AbstractQuantity: ...
    def __lshift__(self, other: Any) -> AbstractQuantity: ...
    def __rlshift__(self, other: Any) -> AbstractQuantity: ...
    def __rshift__(self, other: Any) -> AbstractQuantity: ...
    def __rrshift__(self, other: Any) -> AbstractQuantity: ...
    def __and__(self, other: Any) -> AbstractQuantity: ...
    def __rand__(self, other: Any) -> AbstractQuantity: ...
    def __xor__(self, other: Any) -> AbstractQuantity: ...
    def __rxor__(self, other: Any) -> AbstractQuantity: ...
    def __or__(self, other: Any) -> AbstractQuantity: ...
    def __ror__(self, other: Any) -> AbstractQuantity: ...

    # Comparisons (NumpyComparisonMixin, not overridden)
    def __lt__(self, other: Any) -> Bool[Array, "*shape"]: ...
    def __le__(self, other: Any) -> Bool[Array, "*shape"]: ...
    def __gt__(self, other: Any) -> Bool[Array, "*shape"]: ...
    def __ge__(self, other: Any) -> Bool[Array, "*shape"]: ...

    # Unary (NumpyUnaryMixin)
    def __neg__(self) -> AbstractQuantity: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> AbstractQuantity: ...
    def __invert__(self) -> AbstractQuantity: ...

    # Round/Trunc/Floor/Ceil mixins (the `__round__` *dunder*; `.round()` the
    # method, above, is a distinct member with a different signature)
    def __round__(self, ndigits: int = ...) -> AbstractQuantity: ...
    def __trunc__(self) -> AbstractQuantity: ...
    def __floor__(self) -> AbstractQuantity: ...
    def __ceil__(self) -> AbstractQuantity: ...
    def __format__(self, format_spec: str, /) -> str: ...

class AbstractAngle(AbstractQuantity):
    def wrap_to(
        self, /, min: AbstractQuantity, max: AbstractQuantity
    ) -> AbstractAngle: ...

class Quantity(AbstractQuantity):
    def __init__(self, value: _ValueLike, unit: str | AbstractUnit) -> None: ...
    def __class_getitem__(cls, item: Any) -> type[Self]: ...

    # Repeats `AbstractQuantity.__eq__`/`__ne__` verbatim rather than just
    # inheriting them: pyright infers `q1 == q2` as plain `bool` for a class
    # that doesn't declare `__eq__` in its own body, even though the inherited
    # method is correctly typed (confirmed via `reveal_type(AbstractQuantity.__eq__)`)
    # -- a pyright quirk specific to the equality *operator*, not attribute
    # access. Declaring it here too, identically, is the workaround. Same for
    # `Angle` below.
    def __eq__(self, other: object, /) -> Bool[Array, "*shape"]: ...  # type: ignore[override]
    def __ne__(self, other: object, /) -> Bool[Array, "*shape"]: ...  # type: ignore[override]

Q = Quantity

@final
class StaticQuantity(AbstractQuantity):
    value: StaticValue
    def __init__(
        self, value: _ValueLike | StaticValue, unit: str | AbstractUnit
    ) -> None: ...
    def __eq__(self, other: object, /) -> Any: ...  # type: ignore[override]
    def __ne__(self, other: object, /) -> Any: ...  # type: ignore[override]
    def __hash__(self) -> int: ...

@final
class Angle(AbstractAngle):
    def __init__(self, value: _ValueLike, unit: str | AbstractUnit) -> None: ...
    def __eq__(self, other: object, /) -> Bool[Array, "*shape"]: ...  # type: ignore[override]
    def __ne__(self, other: object, /) -> Bool[Array, "*shape"]: ...  # type: ignore[override]

# ===================================================================
# Module-level functions

def is_any_quantity(obj: Any, /) -> TypeGuard[AbstractQuantity]: ...
def convert_to_quantity_value(obj: Any, /) -> Any: ...
def equivalent(a: AbstractQuantity, b: AbstractQuantity, /) -> Any: ...
def register_ufunc(
    ufunc: np.ufunc, /
) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

# ustrip: no-unit form, unit-first form, and `AllowValue`-flag forms
@overload
def ustrip(x: StaticQuantity, /) -> np.ndarray[Any, Any]: ...
@overload
def ustrip(x: AbstractQuantity, /) -> Array | np.ndarray[Any, Any]: ...
@overload
def ustrip(
    u: str | AbstractUnit | AbstractUnitSystem, x: AbstractQuantity, /
) -> Array | np.ndarray[Any, Any]: ...
@overload
def ustrip(flag: type[AllowValue], x: Any, /) -> Any: ...
@overload
def ustrip(
    flag: type[AllowValue], u: str | AbstractUnit | AbstractUnitSystem, x: Any, /
) -> Any: ...
@overload
def uconvert(u: str | AbstractUnit, x: AbstractQuantity, /) -> AbstractQuantity: ...
@overload
def uconvert(u: AbstractUnitSystem, x: AbstractQuantity, /) -> AbstractQuantity: ...
@overload
def uconvert_value(
    tousys: AbstractUnitSystem, ufrom: str | AbstractUnit, x: ArrayLike, /
) -> ArrayLike: ...
@overload
def uconvert_value(uto: str, ufrom: str, x: ArrayLike, /) -> ArrayLike: ...
@overload
def uconvert_value(
    uto: Any, ufrom: Any, x: AbstractQuantity, /
) -> AbstractQuantity: ...
def is_unit_convertible(to_unit: Any, from_: Any, /) -> bool: ...
def wrap_to(
    angle: AbstractQuantity, min: AbstractQuantity, max: AbstractQuantity, /
) -> AbstractQuantity: ...
