from typing import Any, Generic, LiteralString, Self, TypeVar, overload

import numpy as np
from jaxtyping import Array, Bool
from quax import ArrayValue

from unxt.quantity import StaticValue
from unxt.units import AbstractUnit
from unxt.unitsystems import AbstractUnitSystem

_T = TypeVar("_T", bound=LiteralString)

class AbstractQuantity(ArrayValue):
    # Core public attributes
    value: Array | StaticValue
    unit: AbstractUnit

    # Core public methods
    def uconvert(self, unit: Any) -> Self: ...
    def ustrip(self) -> Any: ...

    # NumpyBinaryOpsMixin
    def __add__(self, other: Any) -> Self: ...
    def __radd__(self, other: Any) -> Self: ...
    def __sub__(self, other: Any) -> Self: ...
    def __rsub__(self, other: Any) -> Self: ...
    def __mul__(self, other: Any) -> AbstractQuantity: ...
    def __rmul__(self, other: Any) -> AbstractQuantity: ...
    def __matmul__(self, other: Any) -> AbstractQuantity: ...
    def __rmatmul__(self, other: Any) -> AbstractQuantity: ...
    def __truediv__(self, other: Any) -> AbstractQuantity: ...
    def __rtruediv__(self, other: Any) -> AbstractQuantity: ...
    def __floordiv__(self, other: Any) -> AbstractQuantity: ...
    def __rfloordiv__(self, other: Any) -> AbstractQuantity: ...
    def __mod__(self, other: Any) -> AbstractQuantity: ...
    def __rmod__(self, other: Any) -> AbstractQuantity: ...
    def __pow__(self, other: Any) -> AbstractQuantity: ...
    def __rpow__(self, other: Any) -> AbstractQuantity: ...

    # NumpyComparisonMixin
    def __eq__(self, other: object) -> Bool[Array, ...]: ...
    def __ne__(self, other: object) -> Bool[Array, ...]: ...  # type: ignore[override]
    def __lt__(self, other: Any) -> Bool[Array, ...]: ...
    def __le__(self, other: Any) -> Bool[Array, ...]: ...
    def __gt__(self, other: Any) -> Bool[Array, ...]: ...
    def __ge__(self, other: Any) -> Bool[Array, ...]: ...

    # NumpyUnaryMixin
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...

    # NumpyRoundMixin / TruncMixin / FloorMixin / CeilMixin
    def __round__(self, ndigits: int = ...) -> Self: ...
    def __trunc__(self) -> Self: ...
    def __floor__(self) -> Self: ...
    def __ceil__(self) -> Self: ...
    @classmethod
    def from_(cls, *args: Any, **kwargs: Any) -> Self: ...

class AbstractParametricQuantity(AbstractQuantity, Generic[_T]): ...
class Quantity(AbstractParametricQuantity[_T]): ...
class Q(AbstractParametricQuantity[_T]): ...
class BareQuantity(AbstractQuantity): ...
class StaticQuantity(AbstractParametricQuantity[_T]): ...
class Angle(Quantity[_T]): ...

@overload
def ustrip(x: AbstractQuantity, /) -> Array | np.ndarray: ...
@overload
def ustrip(
    u: str | AbstractUnit | AbstractUnitSystem, x: AbstractQuantity, /
) -> Array | np.ndarray: ...
def uconvert(
    u: str | AbstractUnit | AbstractUnitSystem, x: AbstractQuantity, /
) -> AbstractQuantity: ...
