name: CD PR - unxts-hypothesis

on:
  pull_request:
    paths:
      - "packages/unxts.hypothesis/**"
      - ".github/workflows/cd-unxts-hypothesis.yml"
      - ".github/workflows/cd-pr-unxts-hypothesis.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

permissions:
  contents: read

jobs:
  build:
    name: Build & inspect package (PR)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # Required for hatch-vcs to determine version from git tags.
          # Can be removed if switching to hardcoded versions.
          fetch-depth: 0
          persist-credentials: false

      - uses: hynek/build-and-inspect-python-package@d44ca7d91762de7a7d5436ddae667c6da6d1c3df # v2.18.0
        with:
          path: packages/unxts.hypothesis
          upload-name-suffix: -unxts-hypothesis
          attest-build-provenance-github: false
